### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by wubuyun** [dadeke/woo-picpay#3]
Para quem acessa o site faz compra com celular ou tablet tbm funciona ou somente no pc?

**Comment by dadeke** [comment]
> 
> 
> Para quem acessa o site faz compra com celular ou tablet tbm funciona ou somente no pc?

@wubuyun ótima pergunta.


Ao finalizar esse plugin eu testei o pagamento usando um celular Android e funcionou.

Infelizmente nesse momento não tenho um iPhone disponível para verifcar se o comportamento é mesmo.

Funciona, mas existe um porém:

* Quando o celular já possui o aplicativo PicPay instalado, ao processar o pagamento o navegador Google Chrome do Android pergunta se deseja abrir o aplicativo. Veja:

<p align="center">
<img src="https://i.imgur.com/tsH3D2W.png" alt="screenshot_1" />
</p>

* É somente selecionar "SEMPRE" e continuar o pagamento normalmente através do aplicativo.

<p align="center">
<img src="https://i.imgur.com/TfPx4qQ.png" alt="screenshot_2" />
</p>

* Mas quando o celular não possui o aplicativo PicPay instalado é possível que apareça essa mensagem:

<p align="center">
<img src="https://i.imgur.com/OaVz86c.png" alt="screenshot_3" />
</p>

Note que nesse caso não aparece o QR Code. 
A leitura do QR Code se faz necessária somente quando o cliente está utilizando o PC.

**Comment by wubuyun** [comment]
Valeu, no futuro vc pretende fazer o modulo para magento ou em algum PWA?

**Comment by dadeke** [comment]
> 
> 
> Valeu, no futuro vc pretende fazer o modulo para magento ou em algum PWA?

@wubuyun 

Módulo para Magento já existe e é mantido pela própria PicPay.
https://github.com/PicPay/magento2

Em algum PWA talvez.
Preciso estudar para ver quais seriam as implicações.

**Comment by wubuyun** [comment]
React
https://github.com/deity-io/falcon
Vue
https://github.com/DivanteLtd/vue-storefront


https://github.com/magento/pwa-studio

**Comment by wubuyun** [comment]
Manual de  integracao vuestorefront

https://docs.vuestorefront.io/guide/integrations/payment-gateway.html#community-resources

Tem um exmplo da paypal do vuestorefront como q integra

https://github.com/develodesign/vsf-payment-paypal
