### ISSUE TITLE
plugins para bagisto

### ISSUE THREAD

**Issue by marcelowu** [dadeke/woo-picpay#4]
pretendi fazer um plugins para bagisto amigo.
https://devdocs.bagisto.com/create_payment_method.html
https://devdocs.bagisto.com/create_package.html
https://github.com/bagisto/bagisto
A Free and Opensource laravel eCommerce framework built for all to build and scale your business. https://bagisto.com

**Comment by dadeke** [comment]
Olá Marcelo.

Caso apareça um _"freelancer"_ pedindo isto, posso sim pensar em fazer.

Obrigado pela sugestão.

**Comment by marcelowu** [comment]
o q eh  freela?
Pic Pay - Laravel 5 https://github.com/LucienCorreia/PicPay

**Comment by dadeke** [comment]
Marcelo.

É _"freelancer"_.

https://www.google.com/search?q=freelancer
