### ISSUE TITLE
encomenda no woocommerce fica com status pendente

### ISSUE THREAD

**Issue by sfortus** [dadeke/woo-picpay#8]
Olá , fiz 2 testes com pagamentos verdadeiros e na minha conta comerciante do picpay os 2 pagamentos ficaram activos mas no meu wocommerce as encomendas ficaram como pendentes.

tenho os tokens gerados e bem introduzidos nos settings de pagamento no meu woocommerce, porque é que as encomendas no meu woocommerce não passaram a pagamento concluido ?

**Comment by dadeke** [comment]
Olá @sfortus 🙂

Isso pode acontecer porque os servidores da PicPay não conseguiram entregar a notificação via **POST** na URL de _callback_ para seu WooCommerce.

Geralmente a causa é devido ao bloqueio de algum firewall.

Então é preciso solicitar ao seu SysAdmin ou ao seu provedor de hospedagem esta liberação.

Também é possível ver alguns relatos sobre esse assunto aqui no fórum:
[https://wordpress.org/support/plugin/woo-picpay/](https://wordpress.org/support/plugin/woo-picpay/
)

**Comment by sfortus** [comment]
obrigado pela sua resposta tao rápida, ja estamos a investigar as configurações do lado do nosso servidor

**Comment by sfortus** [comment]
vimos que o IP da picpay estava a ser bloqueado pelo nosso firewall , agora já comunica , a encomenda ja passou de pendente para em processamento mas devia de passar para concluida.

nos temos um plugin para concluir automaticamente todas as encomendas para concluidas mas nao conseguiu apanhar esta encomenda, porque será ?

porque o vosso plugin não passa a encomenda directamente para concluida ?

**Comment by dadeke** [comment]
>
> nos temos um plugin para concluir automaticamente todas as encomendas para concluidas mas nao conseguiu apanhar esta encomenda, porque será ?
>

O mantenedor deste outro plugin poderá responder esta questão.


> 
> porque o vosso plugin não passa a encomenda directamente para concluida ?
>

Porque isto não é o padrão do WooCommerce.
Este assunto já foi discutido aqui no fórum pelo guru Cláudio Sanches:
[https://wordpress.org/support/topic/pedidos-virtuais-nao-sendo-completados/#post-13500200](https://wordpress.org/support/topic/pedidos-virtuais-nao-sendo-completados/#post-13500200)

**Comment by sfortus** [comment]
obrigado dadeke , sim tem toda a razão , e o problema é da minha plataforma , obrigado pela sua pronta resposta e toda a ajuda dada

**Comment by dadeke** [comment]
Por nada! 🙂
